# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fl_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'fl_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66l_service.proto\x12\tflservice\"\x07\n\x05\x45mpty\"2\n\nFitRequest\x12\x0f\n\x07weights\x18\x01 \x03(\x02\x12\x13\n\x0bnum_samples\x18\x02 \x01(\x05\"H\n\x0b\x46itResponse\x12\x16\n\x0eglobal_weights\x18\x01 \x03(\x02\x12\x12\n\ncategories\x18\x02 \x03(\t\x12\r\n\x05round\x18\x03 \x01(\x05\"4\n\rModelResponse\x12\x0f\n\x07weights\x18\x01 \x03(\x02\x12\x12\n\ncategories\x18\x02 \x03(\t\"\\\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x15\n\rtotal_clients\x18\x03 \x01(\x05\x12\x14\n\x0ctop_category\x18\x04 \x01(\t2\xb3\x01\n\tFLService\x12\x34\n\x03\x46it\x12\x15.flservice.FitRequest\x1a\x16.flservice.FitResponse\x12\x36\n\x08GetModel\x12\x10.flservice.Empty\x1a\x18.flservice.ModelResponse\x12\x38\n\tGetStatus\x12\x10.flservice.Empty\x1a\x19.flservice.StatusResponseB2\n\x1e\x63om.example.federatedapp.protoB\x0e\x46LServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.example.federatedapp.protoB\016FLServiceProtoP\001'
  _globals['_EMPTY']._serialized_start=31
  _globals['_EMPTY']._serialized_end=38
  _globals['_FITREQUEST']._serialized_start=40
  _globals['_FITREQUEST']._serialized_end=90
  _globals['_FITRESPONSE']._serialized_start=92
  _globals['_FITRESPONSE']._serialized_end=164
  _globals['_MODELRESPONSE']._serialized_start=166
  _globals['_MODELRESPONSE']._serialized_end=218
  _globals['_STATUSRESPONSE']._serialized_start=220
  _globals['_STATUSRESPONSE']._serialized_end=312
  _globals['_FLSERVICE']._serialized_start=315
  _globals['_FLSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
