# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fl_service_pb2 as fl__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fl_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FLServiceStub(object):
    """Federated Learning gRPC Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fit = channel.unary_unary(
                '/flservice.FLService/Fit',
                request_serializer=fl__service__pb2.FitRequest.SerializeToString,
                response_deserializer=fl__service__pb2.FitResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/flservice.FLService/GetModel',
                request_serializer=fl__service__pb2.Empty.SerializeToString,
                response_deserializer=fl__service__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/flservice.FLService/GetStatus',
                request_serializer=fl__service__pb2.Empty.SerializeToString,
                response_deserializer=fl__service__pb2.StatusResponse.FromString,
                _registered_method=True)


class FLServiceServicer(object):
    """Federated Learning gRPC Service
    """

    def Fit(self, request, context):
        """Local client sends weights → server returns FedAvg result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Get current global model (for cold-start sync)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Server health / status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fit': grpc.unary_unary_rpc_method_handler(
                    servicer.Fit,
                    request_deserializer=fl__service__pb2.FitRequest.FromString,
                    response_serializer=fl__service__pb2.FitResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=fl__service__pb2.Empty.FromString,
                    response_serializer=fl__service__pb2.ModelResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=fl__service__pb2.Empty.FromString,
                    response_serializer=fl__service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flservice.FLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flservice.FLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FLService(object):
    """Federated Learning gRPC Service
    """

    @staticmethod
    def Fit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flservice.FLService/Fit',
            fl__service__pb2.FitRequest.SerializeToString,
            fl__service__pb2.FitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flservice.FLService/GetModel',
            fl__service__pb2.Empty.SerializeToString,
            fl__service__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flservice.FLService/GetStatus',
            fl__service__pb2.Empty.SerializeToString,
            fl__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
